# Project-wide tooling config (no packaging metadata).

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
# E (pycodestyle errors), F (pyflakes), I (isort via Ruff)
select = ["E", "F", "I"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.ruff.format]
# Black-like formatting without Black
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# Allow long lines in tests and scripts if needed
[tool.ruff.lint.per-file-ignores]
"tests/**" = ["E501"]
"scripts/**" = ["E501"]

[tool.flake8]
max-line-length = 120

[tool.pytest.ini_options]
addopts = "-q -r fEsxX --maxfail=1 --disable-warnings"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
show_missing = true
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
