name: CI (CPU)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cpu:
    name: CPU • ${{ matrix.os }} • py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.12', '3.13']
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install deps
        shell: bash
        run: |
          python -m pip install -U pip ruff
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Ruff (lint + fmt check)
        shell: bash
        run: |
          ruff --version
          ruff check .
          ruff format --check

      - name: Pytest (CPU only; exclude GPU markers)
        env:
          DEVICE: cpu
        shell: bash
        run: |
          pytest -q -m "not gpu and not gpu_cuda and not gpu_mps" --maxfail=1

      - name: Smoke test API (/health) on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        env:
          DEVICE: cpu
          APP_RELOAD: "false"
        shell: bash
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          pid=$!
          python - << 'PY'
          import time, urllib.request, sys
          for _ in range(30):
              try:
                  with urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=1) as r:
                      print(r.read())
                      sys.exit(0)
              except Exception:
                  time.sleep(0.5)
          sys.exit(1)
          PY
                    kill $pid || true
