name: CI (Linux)

on:
  push:
  pull_request:

env:
  # إجبار /matmul وغيرها على العمل بالـ CPU داخل CI
  FORCE_CPU: "1"
  # كاش النماذج لتقليل وقت التحميل
  HF_HOME: ${{ github.workspace }}/models_cache/hf
  TORCH_HOME: ${{ github.workspace }}/models_cache/torch
  TRANSFORMERS_CACHE: ${{ github.workspace }}/models_cache/hf

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Cache model files (HF/Torch)
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.HF_HOME }}
            ${{ env.TORCH_HOME }}
          key: models-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock', '**/requirements*.txt') }}

      # اختر أحد طريقتين التثبيت تلقائيًا حسب ملفات مشروعك
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "pyproject.toml" ] && grep -q "\[tool.poetry\]" pyproject.toml; then
            pip install poetry
            poetry config virtualenvs.create false
            poetry install --no-interaction --no-root
          elif [ -f "pyproject.toml" ]; then
            # PEP 621 + pip/uv style
            pip install -e ".[dev]" || true
            if [ -f "requirements-dev.txt" ]; then pip install -r requirements-dev.txt; fi
            if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          else
            if [ -f "requirements-dev.txt" ]; then pip install -r requirements-dev.txt; fi
            if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          fi
          # أدوات إضافية متوقعة
          pip install pre-commit pytest httpx uvicorn ruff

      - name: Lint & format (pre-commit)
        run: |
          pre-commit run --all-files

      - name: Run tests (fast path)
        env:
          PYTEST_ADDOPTS: "-q --maxfail=1"
        run: |
          pytest || pytest -k "not slow"

      # اختياري: ارفع تقارير (JUnit) إن وُجدت
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: |
            **/pytest.xml
            **/.pytest_cache
          if-no-files-found: ignore
