name: CI • Windows

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows • py${{ matrix.python }}
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python: ['3.12']
    env:
      PYTHONPATH: ${{ github.workspace }}
      DEVICE: cpu
      APP_RELOAD: "false"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install deps
        shell: powershell
        run: |
          python -m pip install -U pip ruff
          pip install -r requirements.txt
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }

      - name: Ruff (lint + fmt check)
        shell: powershell
        run: |
          ruff --version
          ruff check .
          ruff format --check

      - name: Pytest (CPU only)
        shell: powershell
        run: |
          pytest -q -m "not gpu and not gpu_cuda and not gpu_mps" --maxfail=1

      - name: Smoke test API (/health)
        shell: powershell
        run: |
          $proc = Start-Process -FilePath uvicorn -ArgumentList "app.main:app --host 127.0.0.1 --port 8000" -PassThru
          python - << 'PY'
          import time, urllib.request, sys
          for _ in range(30):
              try:
                  with urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=1) as r:
                      print(r.read())
                      sys.exit(0)
              except Exception:
                  time.sleep(0.5)
          sys.exit(1)
          PY
          if ($proc) { Stop-Process -Id $proc.Id -Force }
