name: CI (Windows)

on:
  push:
  pull_request:

env:
  FORCE_CPU: "1"
  HF_HOME: 'C:\models_cache\hf'
  TORCH_HOME: 'C:\models_cache\torch'
  TRANSFORMERS_CACHE: 'C:\models_cache\hf'

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Prepare caches
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path $env:HF_HOME | Out-Null
          New-Item -ItemType Directory -Force -Path $env:TORCH_HOME | Out-Null

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache model files (HF/Torch)
        uses: actions/cache@v4
        with:
          path: |
            C:\models_cache\hf
            C:\models_cache\torch
          key: models-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock', '**/requirements*.txt') }}

      - name: Upgrade pip & base tools
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest httpx uvicorn ruff

      - name: Install dependencies (Poetry / PEP621 / requirements)
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'

          # هل المشروع يستخدم Poetry؟
          $usesPoetry = (Test-Path "pyproject.toml") -and (Select-String -Path "pyproject.toml" -Pattern '\[tool\.poetry\]' -Quiet)

          if ($usesPoetry) {
            pip install poetry
            poetry config virtualenvs.create false

            # هل عندك group dev في Poetry؟
            $hasDevGroup = (Select-String -Path "pyproject.toml" -Pattern '^\s*\[tool\.poetry\.group\.dev\]' -Quiet)
            if ($hasDevGroup) {
              poetry install --no-interaction --no-root --with dev
            } else {
              poetry install --no-interaction --no-root
            }
          }
          elseif (Test-Path "pyproject.toml") {
            # مشروع PEP621: هل يوجد extra 'dev' فعلاً؟
            $hasDevExtra = python -c "import tomllib,sys; from pathlib import Path as P; d=tomllib.loads(P('pyproject.toml').read_text('utf-8')); print('1' if d.get('project',{}).get('optional-dependencies',{}).get('dev') else '0')"
            if ($hasDevExtra -eq '1') {
              pip install -e ".[dev]"
            } else {
              pip install -e "."
            }
            if (Test-Path "requirements-dev.txt") { pip install -r requirements-dev.txt }
            if (Test-Path "requirements.txt")     { pip install -r requirements.txt }
          }
          else {
            if (Test-Path "requirements-dev.txt") { pip install -r requirements-dev.txt }
            if (Test-Path "requirements.txt")     { pip install -r requirements.txt }
          }

      - name: Lint & format (pre-commit)
        shell: powershell
        run: pre-commit run --all-files

      - name: Run tests (fast path)
        shell: powershell
        env:
          PYTEST_ADDOPTS: "-q --maxfail=1"
        run: |
          $ErrorActionPreference = 'Continue'
          pytest
          if ($LASTEXITCODE -ne 0) {
            pytest -k "not slow"
          }

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-windows
          path: |
            **/pytest.xml
            **/.pytest_cache
          if-no-files-found: ignore
